### PR TITLE
Use dash uri for zeal

### LINKED ISSUE #54: Zeal dosn't open
Zeal dosn't open with the shortcut.

Zeal in v3.0 dropped support for `--query`
https://github.com/zealdocs/zeal/releases/tag/v0.3.0

Maybe just drop this line
https://github.com/gdelmas/IntelliJDashPlugin/blob/master/src/de/dreamlab/dash/launcher/ZealLauncher.java#L36

I was unable to compile the plugin in my old Java environment, so I wasn't able to test if this would work.

Kind regards

### PR DESCRIPTION
**Pull request by symptog**
Remove ZealLauncher because Zeal > 0.3.0 supports the dash uri schema.
I build the plugin and it works like a charm.

fixed #54
may work in windows with zeal too (#36) but not tested

### CODE REVIEW

**Comment by cvuorinen** [comment]
ping @gdelmas 
Would be nice if you could look into this. Currently the plugin is not working on Linux at all (if Zeal > 0.3.0)

**Comment by symptog** [comment]
@cvuorinen you manually can install a fixed version: https://github.com/symptog/IntelliJDashPlugin/releases/tag/3.2.4

**Comment by grobinson-r7** [comment]
@symptog what are build steps for personal reference?

**Comment by symptog** [comment]
You can find a .jar in my fork; in the releases

Am 1. März 2017 12:23:17 MEZ schrieb Gary Robinson <notifications@github.com>:
>@symptog what are build steps for personal reference?

**Pull request merged**
